version: '3'

services:
  postgres_vault:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dbvault
    volumes:
      - vault_pgsql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vault:
    image: vault
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: "http://vault:8200"
      VAULT_SKIP_VERIFY: "true"
      VAULT_API_ADDR: "http://vault:8200"
      VAULT_REDIRECT_ADDR: "http://vault:8200"
      STORAGE: "postgresql"
      PG_USER: "postgres"
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: "dbvault"
      PG_HOST: "postgres_vault"
      PG_PORT: "5432"
      PG_SSLMODE: "verify-full"
      PG_SSLCERT: "/etc/vault/certs/vault.crt"
      PG_SSLKEY: "/etc/vault/certs/vault.key"
      PG_SSLROOTCERT: "/etc/vault/certs/ca.crt"
      HA_ENABLED: "true"
      HA_MODE: "external"
      HA_EXTERNAL_VIP: "192.168.0.1"
      SEAL_TYPE: "pkcs11"
      PKCS11_LIB: "/usr/lib/softhsm/libsofthsm2.so"
      PKCS11_SLOT: "0"
      PKCS11_PIN: ${PKCS11_PIN}
    volumes:
      - vault_data:/vault/data
      - ./vault-certs:/etc/vault/certs
    ports:
      - "8200:8200"

volumes:
  vault_data:
  vault_pgsql_data:
